/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Data {
  'id' : Id,
  'status' : Status,
  'jobDescriptionId' : Id,
  'createdAt' : bigint,
  'recruiterId' : Principal,
  'matchScore' : bigint,
  'resumeId' : Id,
  'candidateName' : string,
  'matchedSkills' : Array<string>,
}
export interface Data__1 {
  'id' : Id,
  'rawText' : string,
  'education' : Array<string>,
  'recruiterId' : Principal,
  'fileName' : string,
  'experience' : Array<string>,
  'candidateName' : string,
  'certifications' : Array<string>,
  'skills' : Array<string>,
  'uploadedAt' : bigint,
}
export interface Data__2 {
  'id' : Id,
  'title' : string,
  'createdAt' : bigint,
  'recruiterId' : Principal,
  'description' : string,
  'qualifications' : Array<string>,
  'requiredSkills' : Array<string>,
}
export type Id = bigint;
export type Status = { 'pending' : null } |
  { 'rejected' : null } |
  { 'shortlisted' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addJobDescription' : ActorMethod<
    [string, string, Array<string>, Array<string>, bigint],
    Data__2
  >,
  'addResume' : ActorMethod<
    [
      string,
      string,
      string,
      Array<string>,
      Array<string>,
      Array<string>,
      Array<string>,
      bigint,
    ],
    Data__1
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'batchMatch' : ActorMethod<[Id], Array<Data>>,
  'deleteJobDescription' : ActorMethod<[Id], undefined>,
  'deleteResume' : ActorMethod<[Id], undefined>,
  'getAllCandidateResultsByJob' : ActorMethod<[Id], Array<Data>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCandidateResultsByJobAndStatus' : ActorMethod<[Id, Status], Array<Data>>,
  'getJobDescription' : ActorMethod<[Id], Data__2>,
  'getResume' : ActorMethod<[Id], Data__1>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listJobDescriptions' : ActorMethod<[], Array<Data__2>>,
  'listResumes' : ActorMethod<[], Array<Data__1>>,
  'matchResumeToJob' : ActorMethod<[Id, Id], Data>,
  'rejectCandidate' : ActorMethod<[Id], Data>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'shortlistCandidate' : ActorMethod<[Id], Data>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];