/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Id = IDL.Nat;
export const Data__2 = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'recruiterId' : IDL.Principal,
  'description' : IDL.Text,
  'qualifications' : IDL.Vec(IDL.Text),
  'requiredSkills' : IDL.Vec(IDL.Text),
});
export const Data__1 = IDL.Record({
  'id' : Id,
  'rawText' : IDL.Text,
  'education' : IDL.Vec(IDL.Text),
  'recruiterId' : IDL.Principal,
  'fileName' : IDL.Text,
  'experience' : IDL.Vec(IDL.Text),
  'candidateName' : IDL.Text,
  'certifications' : IDL.Vec(IDL.Text),
  'skills' : IDL.Vec(IDL.Text),
  'uploadedAt' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Status = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'shortlisted' : IDL.Null,
});
export const Data = IDL.Record({
  'id' : Id,
  'status' : Status,
  'jobDescriptionId' : Id,
  'createdAt' : IDL.Int,
  'recruiterId' : IDL.Principal,
  'matchScore' : IDL.Nat,
  'resumeId' : Id,
  'candidateName' : IDL.Text,
  'matchedSkills' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addJobDescription' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text), IDL.Int],
      [Data__2],
      [],
    ),
  'addResume' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Int,
      ],
      [Data__1],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'batchMatch' : IDL.Func([Id], [IDL.Vec(Data)], []),
  'deleteJobDescription' : IDL.Func([Id], [], []),
  'deleteResume' : IDL.Func([Id], [], []),
  'getAllCandidateResultsByJob' : IDL.Func([Id], [IDL.Vec(Data)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCandidateResultsByJobAndStatus' : IDL.Func(
      [Id, Status],
      [IDL.Vec(Data)],
      ['query'],
    ),
  'getJobDescription' : IDL.Func([Id], [Data__2], ['query']),
  'getResume' : IDL.Func([Id], [Data__1], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listJobDescriptions' : IDL.Func([], [IDL.Vec(Data__2)], ['query']),
  'listResumes' : IDL.Func([], [IDL.Vec(Data__1)], ['query']),
  'matchResumeToJob' : IDL.Func([Id, Id], [Data], []),
  'rejectCandidate' : IDL.Func([Id], [Data], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'shortlistCandidate' : IDL.Func([Id], [Data], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Id = IDL.Nat;
  const Data__2 = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'recruiterId' : IDL.Principal,
    'description' : IDL.Text,
    'qualifications' : IDL.Vec(IDL.Text),
    'requiredSkills' : IDL.Vec(IDL.Text),
  });
  const Data__1 = IDL.Record({
    'id' : Id,
    'rawText' : IDL.Text,
    'education' : IDL.Vec(IDL.Text),
    'recruiterId' : IDL.Principal,
    'fileName' : IDL.Text,
    'experience' : IDL.Vec(IDL.Text),
    'candidateName' : IDL.Text,
    'certifications' : IDL.Vec(IDL.Text),
    'skills' : IDL.Vec(IDL.Text),
    'uploadedAt' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Status = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'shortlisted' : IDL.Null,
  });
  const Data = IDL.Record({
    'id' : Id,
    'status' : Status,
    'jobDescriptionId' : Id,
    'createdAt' : IDL.Int,
    'recruiterId' : IDL.Principal,
    'matchScore' : IDL.Nat,
    'resumeId' : Id,
    'candidateName' : IDL.Text,
    'matchedSkills' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addJobDescription' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text), IDL.Int],
        [Data__2],
        [],
      ),
    'addResume' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Int,
        ],
        [Data__1],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'batchMatch' : IDL.Func([Id], [IDL.Vec(Data)], []),
    'deleteJobDescription' : IDL.Func([Id], [], []),
    'deleteResume' : IDL.Func([Id], [], []),
    'getAllCandidateResultsByJob' : IDL.Func([Id], [IDL.Vec(Data)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCandidateResultsByJobAndStatus' : IDL.Func(
        [Id, Status],
        [IDL.Vec(Data)],
        ['query'],
      ),
    'getJobDescription' : IDL.Func([Id], [Data__2], ['query']),
    'getResume' : IDL.Func([Id], [Data__1], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listJobDescriptions' : IDL.Func([], [IDL.Vec(Data__2)], ['query']),
    'listResumes' : IDL.Func([], [IDL.Vec(Data__1)], ['query']),
    'matchResumeToJob' : IDL.Func([Id, Id], [Data], []),
    'rejectCandidate' : IDL.Func([Id], [Data], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'shortlistCandidate' : IDL.Func([Id], [Data], []),
  });
};

export const init = ({ IDL }) => { return []; };